core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.views.static import serve




urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm
from django.contrib.auth import logout


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })
    
def logout_view(request):
    logout(request)
    return redirect('/')

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home Netmarketplace</title>
    <link rel="stylesheet" href="https://bennymarketplacebucket.s3.amazonaws.com/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap">
    <link rel="stylesheet" href="https://bennymarketplacebucket.s3.amazonaws.com/assets/fonts/simple-line-icons.min.css">
    <link rel="stylesheet" href="https://bennymarketplacebucket.s3.amazonaws.com/assets/css/baguetteBox.min.css">
    <link rel="stylesheet" href="https://bennymarketplacebucket.s3.amazonaws.com/assets/css/smoothproducts.css">

    <style>
        body {
            background-color: #333333;
        }

        .clean-block.clean-form.dark {
            background-color: #666666;
        }

        .page-content {
            padding-top: 70px;
            color: grey;
        }

        a {
            color: blue;
        }
    </style>
</head>

<body>
    {% include 'includes/navbar.html' %}

    <main class="page landing-page">
        <section class="clean-block clean-form dark">
            <div class="container">
                    {% block content %}
                    {% endblock %}
            </div>
        </section>
    </main>

    {% include 'includes/footer.html' %}

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://bennymarketplacebucket.s3.amazonaws.com/assets/js/baguetteBox.min.js"></script>
    <script src="https://bennymarketplacebucket.s3.amazonaws.com/assets/js/smoothproducts.min.js"></script>
    <script src="https://bennymarketplacebucket.s3.amazonaws.com/assets/js/theme.js"></script>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}Welcome{% endblock %}

{% block content %}
<style>
.page-content {
  padding-top: 70px; /* Adjust the value as needed */
}
</style>
<main class="page landing-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-100 rounded-xl">
                    <div class="card-body">
                        <h2 class="mb-4 text-2xl text-center">Newest items</h2>
                        <div class="row">
                            {% for item in items %}
                            <div class="col-md-4">
                                <a href="{% url 'item:detail' item.id %}">
                                    <div class="card">
                                        <img src="{{ item.image.url }}" class="card-img-top rounded-top-xl" alt="{{ item.name }}">
                                        <div class="card-body">
                                            <h2 class="card-title">{{ item.name }}</h2>
                                            <p class="card-text">Price: {{ item.price }}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <section class="clean-block slider dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-info">Products</h2>
                    <p>These are some of the products</p>
                </div>
                <div id="carousel-1" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for item in items %}
                        <div class="carousel-item{% if forloop.first %} active{% endif %}">
                            <a href="{% url 'item:detail' item.id %}">
                                <div class="card">
                                    <img src="{{ item.image.url }}" class="card-img-top rounded-top-xl" alt="{{ item.name }}">
                                    <div class="card-body">
                                        <h2 class="card-title">{{ item.name }}</h2>
                                        <p class="card-text">Price: {{ item.price }}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}                        
                    </div>
                    <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    <ol class="carousel-indicators">
                        {% for item in items %}
                        <li data-target="#carousel-1" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </section>
        
    
    



        <div class="row mt-6">
            <div class="col-md-12">
                <div class="card bg-gray-100 rounded-xl">
                    <div class="card-body">
                        <h2 class="mb-4 text-2xl text-center">Categories</h2>
                        <div class="row">
                            {% for category in categories %}
                            <div class="col-md-4 {% if category.id == category_id %} bg-gray-200{% endif %}">
                                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                                    <div class="card">
                                        <div class="card-body">
                                            <h2 class="card-title">{{ category.name }}</h2>
                                            <p class="card-text">{{ category.items.count }} items</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="form-label">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="form-label">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="form-label">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="form-label">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}