conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.views.static import serve




urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

item/models.py
from django.contrib.auth.models import User
from django.db import models

from storages.backends.s3boto3 import S3Boto3Storage

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return str(self.name)




class CustomS3Boto3Storage(S3Boto3Storage):
    location = 'media'

    def get_object_parameters(self, name):
        params = super(CustomS3Boto3Storage, self).get_object_parameters(name)
        if 'ACL' in params:
            del params['ACL']
        return params

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='media/', blank=True, null=True, storage=CustomS3Boto3Storage())
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField(default=0.0)
    full_description = models.TextField(blank=True, null=True)
    full_description_photo = models.ImageField(upload_to='media/', blank=True, null=True, storage=CustomS3Boto3Storage())
    def __str__(self):
        return str(self.name)

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image','full_description','full_description_photo',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'full_description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'full_description_photo': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold','full_description','full_description_photo',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'full_description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'full_description_photo': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Category, Item

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <div class="card mb-4">
            <div class="rating">
                <img src="/static/assets/img/star.svg">
                <img src="/static/assets/img/star.svg">
                <img src="/static/assets/img/star.svg">
                <img src="/static/assets/img/star-half-empty.svg">
                <img src="/static/assets/img/star-empty.svg">
            </div>

            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
            <div class="card-body">
                <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
                <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
                <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>

                {% if item.description %}
                    <p class="text-gray-700">
                        <strong class="text-gray-500">Description:</strong><br>
                        {{ item.description }}
                    </p>
                {% endif %}

                {% if request.user == item.created_by %}
                    <div class="mt-6 p-6 bg-white rounded-xl">
                        <p>This is your item!</p>
                        <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-blue rounded-xl">Edit</a>
                        <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-blue rounded-xl">Delete</a>
                    </div>
                {% else %}  
                    <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-blue rounded-xl hover:bg-teal-700">Contact seller</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="product-info">
            <div>
                <ul class="nav nav-tabs" role="tablist" id="myTab">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" role="tab" data-toggle="tab" id="description-tab" href="#description">Full Description</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" role="tab" data-toggle="tab" id="specifications-tabs" href="#specifications">Specifications</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" role="tab" data-toggle="tab" id="reviews-tab" href="#reviews">Reviews</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" role="tab" data-toggle="tab" id="related-items-tab" href="#related-items">Related Items</a>
                    </li>
                </ul>

                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active description" role="tabpanel" id="description">
                        {% if item.full_description == null %}
                        <p>{{ item.full_description }}</p>
                        {% endif %}
                        {% if item.full_description_photo %}
                            <div class="row">
                                <div class="col-md-5">
                                    <figure class="figure">
                                        <img class="img-fluid figure-img" src="{{ item.full_description_photo.url }}" alt="Full Description Photo">
                                    </figure>                                        
                                </div>
                                <div class="col-md-7">
                                    <h4>{{item.name}}</h4>
                                    <br>
                                    <h5>{{item.category}}</h5>
                                    <br>
                                    <p>{{ item.full_description }}</p>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="tab-pane fade specifications" role="tabpanel" id="specifications">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td class="stat">Display</td>
                                        <td>5.2"</td>
                                    </tr>
                                    <tr>
                                        <td class="stat">Camera</td>
                                        <td>12MP</td>
                                    </tr>
                                    <tr>
                                        <td class="stat">RAM</td>
                                        <td>4GB</td>
                                    </tr>
                                    <tr>
                                        <td class="stat">OS</td>
                                        <td>iOS</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="reviews">
                        <div class="reviews">
                            <div class="review-item">
                                <div class="rating">
                                    <img src="{% static 'assets/img/star.svg' %}">
                                    <img src="{% static 'assets/img/star.svg' %}">
                                    <img src="{% static 'assets/img/star.svg' %}">
                                    <img src="{% static 'assets/img/star.svg' %}">
                                    <img src="{% static 'assets/img/star-empty.svg' %}">
                                </div>
                                <h4>Incredible product</h4>
                                <span class="text-muted"><a href="#">John Smith</a>, 20 Jan 2018</span>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec augue nunc, pretium at augue at, convallis pellentesque ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" role="tabpanel" id="related-items">

                        <div class="row">
                            {% for related_item in related_items %}
                                <div class="col-md-4">
                                    <a href="{% url 'item:detail' related_item.id %}">
                                        <div class="card mb-4">
                                            <img src="{{ related_item.image.url }}" class="card-img-top" alt="{{ related_item.name }}">
                                            <div class="card-body">
                                                <h2 class="card-title h5">{{ related_item.name }}</h2>
                                                <p class="card-text">Price: {{ related_item.price }}</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

{% if user.is_authenticated and user.is_staff %}  <!-- Check if user is authenticated and is staff (admin) -->
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="alert alert-danger mb-3 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn btn-primary mt-6 py-3 px-6 text-lg rounded-xl">Submit</button>
    </form>
{% else %}
    <div class="alert alert-info mt-3 rounded-xl">
        You need to be an admin to add new items.
    </div>
{% endif %}
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <form method="get" action="{% url 'item:items' %}">
                        <div class="form-group">
                            <input name="query" class="form-control" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">
                        </div>

                        <button class="btn btn-primary" type="submit">Search</button>
                    </form>

                    <hr class="my-4">

                    <p class="font-weight-bold">Categories</p>

                    <ul class="list-unstyled">
                        {% for category in categories %}
                            <li class="py-2 px-2{% if category.id == category_id %} bg-gray-200{% endif %}">
                                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>

                    <hr class="my-4">

                    <p class="font-weight-bold">Clear filters</p>

                    <ul class="list-unstyled">
                        <li>
                            <a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 btn btn-warning btn-lg btn-block text-white">Clear</a>
                        </li>
                    </ul>
                </div>



                <section class="clean-block slider dark">
                    <div class="container">
                        <div class="block-heading">
                            <h2 class="text-info">Products</h2>
                            <p>These are some of the products</p>
                        </div>
                        <div id="carousel-1" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for item in items %}
                                <div class="carousel-item{% if forloop.first %} active{% endif %}">
                                    <a href="{% url 'item:detail' item.id %}">
                                        <div class="card">
                                            <img src="{{ item.image.url }}" class="card-img-top rounded-top-xl" alt="{{ item.name }}">
                                            <div class="card-body">
                                                <h2 class="card-title">{{ item.name }}</h2>
                                                <p class="card-text">Price: {{ item.price }}</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                            <ol class="carousel-indicators">
                                {% for item in items %}
                                <li data-target="#carousel-1" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                </section>
                
        



                <div class="col-md-9">
                    <div class="row">
                        {% for item in items %}
                            <div class="col-md-4">
                                <a href="{% url 'item:detail' item.id %}">
                                    <div class="card mb-4">
                                        <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                                        <div class="card-body">
                                            <h2 class="card-title h5">{{ item.name }}</h2>
                                            <p class="card-text">Price: {{ item.price }}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}